[SERV-464] Update security issues, fix tests
UCLALibrary/hauth pull request #41
Opened 2022-06-07 14:12 UTC by ksclarke

* Update Alpine image version
* Update Vert.x version
* Update ItemsHandler as a result of the Vert.x version update
* Remove the mid-method return in ItemsHandler
* Fix asynchronous asserts in tests
* Get rid of TestConstants class; use freelib-utils' constant instead
* Eclipse sorted some import statements

2022-06-08 19:30 UTC, ksclarke commented
Marked as draft just to do some sanity checks to make sure I didn't mangle anything with the other PR merge.

2022-06-08 21:01 UTC, markmatney requested changes

2022-06-08 21:01 UTC, markmatney commented on src/test/java/edu/ucla/library/iiif/auth/utils/TestUtils.java
> +     *      "https://github.com/UCLALibrary/sinaimanuscripts/blob/main/app/controllers/application_controller.rb">How
Per our side channel discussion @ksclarke : 
```suggestion
     *      "https://github.com/UCLALibrary/sinaimanuscripts/blob/v2.15.7/app/controllers/application_controller.rb">How
```

2022-06-08 21:02 UTC, markmatney commented on src/test/java/edu/ucla/library/iiif/auth/utils/TestUtils.java
> +     *      "https://github.com/UCLALibrary/sinaimanuscripts/blob/main/app/controllers/application_controller.rb">How
Or comment in code instead is fine w/ me if you prefer

2022-06-08 21:02 UTC, ksclarke commented on src/test/java/edu/ucla/library/iiif/auth/utils/TestUtils.java
> +     *      "https://github.com/UCLALibrary/sinaimanuscripts/blob/main/app/controllers/application_controller.rb">How
See ongoing discussion... I really think this should be a comment in the code (to the tagged version, yes) instead of a see tag which I see as more linking to real documentation.

2022-06-09 03:59 UTC, ksclarke commented
Made this a draft again because I forgot to add an explanation about the cookie format and the link to the Hyrax code in the README and test configs in the POM. Will do this in the AM.

2022-06-09 22:16 UTC, markmatney approved these changes

2022-06-09 23:59 UTC, DRickard approved these changes

2022-06-10 00:11 UTC, merged